pipeline {
    agent any
    environment {
        GITHUB_CREDS = 'github-token'
        DOCKER_CREDS = 'dockerhub-creds'
        REPO_URL = 'https://github.com/diaamohammad/alx-backend-python.git'
        DOCKER_IMAGE_NAME = 'diaaalsemary5/messaging-app'
    }
    stages {
        stage('1. Checkout Code') {
            steps {
                git url: REPO_URL, credentialsId: GITHUB_CREDS, branch: 'main'
            }
        }
        stage('2. Run Tests (pytest)') {
            steps {
                dir('messaging_app') {
                    // تثبيت بايثون يدوياً لتجاوز مشكلة البلاجن
                    sh '''
                        apt-get update
                        apt-get install -y python3-pip python3-dev
                        pip3 install -r requirements.txt
                        pip3 install pytest coverage
                        
                        pytest --junitxml=test-report.xml || true
                    '''
                }
            }
            post {
                always {
                    junit 'messaging_app/test-report.xml'
                }
            }
        }
        stage('3. Build Docker Image') {
            steps {
                dir('messaging_app') {
                    script {
                        docker.build("${DOCKER_IMAGE_NAME}:${env.BUILD_NUMBER}", ".")
                    }
                }
            }
        }
        stage('4. Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', DOCKER_CREDS) {
                        docker.image("${DOCKER_IMAGE_NAME}:${env.BUILD_NUMBER}").push()
                        docker.image("${DOCKER_IMAGE_NAME}:latest").push()
                    }
                }
            }
        }
    }
}
