#!/bin/bash
echo "--- Deploying BLUE version (v1) ---"
kubectl apply -f blue_deployment.yaml

echo "--- Deploying GREEN version (v2) ---"
kubectl apply -f green_deployment.yaml

echo "--- Applying Service (directing traffic to BLUE) ---"
kubectl apply -f kubeservice.yaml

echo "--- Checking logs for new (GREEN) version for errors ---"
kubectl logs -l app=messaging-app,version=green --tail=10
